version: '3.8'

services:
  editaliza-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: editaliza-production
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_PATH=/app/data/database.db
    volumes:
      # Persistent database storage
      - editaliza-data:/app/data
      # Logs volume
      - editaliza-logs:/app/logs
    secrets:
      - session_secret
      - jwt_secret
    networks:
      - editaliza-network
    healthcheck:
      test: ["CMD", "node", "-e", "const http=require('http');http.get('http://localhost:3000/health',(r)=>{process.exit(r.statusCode===200?0:1)}).on('error',()=>process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Optional: Redis for session storage (recommended for production)
  redis:
    image: redis:7-alpine
    container_name: editaliza-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    networks:
      - editaliza-network
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: editaliza-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - editaliza-app
    networks:
      - editaliza-network

volumes:
  editaliza-data:
    driver: local
  editaliza-logs:
    driver: local
  redis-data:
    driver: local

secrets:
  session_secret:
    file: ./secrets/session_secret.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt

networks:
  editaliza-network:
    driver: bridge